server:
  port: 8085

spring:
  application:
    name: notification-service

  profiles:
    active: dev

  rabbitmq:
    username: rmuser
    password: rmpassword

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:9000/eureka
  instance:
    prefer-ip-address: true

management:
  tracing:
    sampling:
      probability: 1.0