scrape_configs:
  - job_name: 'spring-boot-application-metrics'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 2s
    static_configs:
      - targets: ['host.docker.internal:8082']
